### ISSUE TITLE
Exploration: Connecting Community XYZ with verto

### ISSUE THREAD

**Issue by michael-spengler** [CommunityXYZ/community-js#1]
Hi. I'm very new to this so please forgive me if it is a stupid question:

I created my first community with the following transaction: 
https://viewblock.io/arweave/tx/g38_f-zQiDFqKV0iELjZk8QqtDqhWq3siAdDYw87OHY

Then I went to verto thinking that the tokens I minted there should be immediately visible.

This seems not to be the case. Where is my misconception? :)

**Comment by michael-spengler** [comment]
This issue might be related to https://github.com/CommunityXYZ/website/issues/9

**Comment by cedriking** [comment]
Hello @michael-spengler you can go to https://verto.exchange/tokens and ask to add your tokens there, a vote will be created for this. Any further questions related to Verto should be asked on their Discord or as an issue on their repo: https://github.com/useverto/verto
