### ISSUE TITLE
Cannot unlock vault

### ISSUE THREAD

**Issue by layinka** [CommunityXYZ/community-js#10]
Hi,
I am trying to unlock the PSTs i left in the vault.

i have tried both with the community xyz dapp and with the js library, its not working and the vault balance is still locked.

Also if i check the vaultbalance with the js ibrary,it says 0, but viewblock and communityxyz are still showing that the PSTs are still locked.
Also, when i check the state of the weave contract,its still showing the PSts are in the vault

**Comment by layinka** [comment]
Any luck with this,

It still seems unresolved

**Comment by cedriking** [comment]
Hey Layinka, this has been resolved a long time ago. That's why I closed the issue here. It was due to a caching issue happening on the server we were used to cache smartweave states.

**Comment by layinka** [comment]
Ok, thanks
